version: 2

models:
  - name: stg_customers
    description: "Staging table for customer data from CRM system"
    columns:
      - name: customer_id
        description: "Unique identifier for each customer"
        tests:
          - unique
          - not_null
      - name: customer_unique_id
        description: "Alternative customer identifier"
        tests:
          - not_null
      - name: customer_zip_code_prefix
        description: "Customer zip code prefix"
        tests:
          - not_null

  - name: stg_orders
    description: "Staging table for order data from ERP system"
    columns:
      - name: order_id
        description: "Unique identifier for each order"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key to customer"
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: order_status
        description: "Current status of the order"
        tests:
          - not_null
          - accepted_values:
              values: ['delivered', 'shipped', 'processing', 'canceled', 'unavailable', 'invoiced', 'approved', 'created']
      - name: order_purchase_timestamp
        description: "Timestamp when order was purchased"
        tests:
          - not_null

  - name: stg_payments
    description: "Staging table for payment data from streaming system"
    columns:
      - name: payment_key
        description: "Unique payment identifier (order_id + payment_sequential)"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "Order identifier for payment"
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_id
      - name: payment_sequential
        description: "Sequential number of payment for order"
        tests:
          - not_null
      - name: payment_type
        description: "Type of payment method used"
        tests:
          - not_null
          - accepted_values:
              values: ['credit_card', 'boleto', 'voucher', 'debit_card', 'not_defined']
      - name: payment_installments
        description: "Number of payment installments"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 24
      - name: payment_value
        description: "Payment amount in BRL"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 50000
      - name: data_source
        description: "Source of payment data (batch or streaming)"
        tests:
          - not_null
          - accepted_values:
              values: ['batch', 'streaming']

  - name: stg_order_items
    description: "Staging table for order item details"
    columns:
      - name: order_id
        description: "Order identifier"
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_id
      - name: order_item_id
        description: "Sequential item number within order"
        tests:
          - not_null
      - name: product_id
        description: "Product identifier"
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id
      - name: price
        description: "Item price"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 10000

  - name: stg_products
    description: "Staging table for product catalog data"
    columns:
      - name: product_id
        description: "Unique product identifier"
        tests:
          - unique
          - not_null
      - name: product_category_name
        description: "Product category"
        tests:
          - not_null

  - name: stg_reviews
    description: "Staging table for review data from API"
    columns:
      - name: review_id
        description: "Unique review identifier"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "Order being reviewed"
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_id
      - name: review_score
        description: "Review rating from 1-5"
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5]
