olist_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'postgres') }}"
      user: "{{ env_var('POSTGRES_USER', 'olist') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'olist123') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | as_number }}"
      dbname: "{{ env_var('POSTGRES_DB', 'olist_dw') }}"
      schema: public
      threads: 1
